database:
  default-timeout-time: 1
  enable-exec-cmd: true
  show-password: false
  print-exception-by-ping: true
  list:
    local: 
      url: jdbc:sqlite:local_db.sqlite
      user: 
      password: 
      timeout-time: -1
      alive-monitoring: -1
    remote: 
      url: 
      user: 
      password: 
      timeout-time: 3
      alive-monitoring: 600